name: CD - Deploy to Ghost
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          echo yarn version $(yarn -v)
          yarn
      - name: Run Tests
        run: yarn test:ci

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        languages: [
            # ENGLISH,
            # CHINESE,
            # ESPANOL,
            ITALIAN,
            # PORTUGUESE,
            # JAPANESE,
            # ARABIC,
            # URDU,
            BENGALI
          ]

    env:
      ITALIAN_GHOST_ADMIN_API_URL: ${{ secrets.ITALIAN_GHOST_ADMIN_API_URL }}
      ITALIAN_GHOST_ADMIN_API_KEY: ${{ secrets.ITALIAN_GHOST_ADMIN_API_KEY }}
      BENGALI_GHOST_ADMIN_API_URL: ${{ secrets.BENGALI_GHOST_ADMIN_API_URL }}
      BENGALI_GHOST_ADMIN_API_KEY: ${{ secrets.BENGALI_GHOST_ADMIN_API_KEY }}

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.3.1
        with:
          api-url: ${{ env.${{ matrix.languages }}_GHOST_ADMIN_API_URL }}
          api-key: ${{ env.${{ matrix.languages }}_GHOST_ADMIN_API_KEY }}
